spring:
  application:
    name: dubbo-provider
  main:
    web-application-type: none
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
#    address: ${DUBBO_REGISTRY_ADDRESS:zookeeper://localhost:2181}
    address: ${DUBBO_REGISTRY_ADDRESS:nacos://localhost:8848}
    check: false
    register-mode: instance
  provider:
    timeout: 1000
