spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: test_
      use-key-prefix: true
      cache-null-values: true
  redis:
    host: localhost
    port: 6379
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enabled: true
